#!/bin/sh
BRANCH=$(git branch --show-current)
PKG="$(git rev-parse --show-toplevel)/package.json"

case "$BRANCH" in
  DEV)
    HOOK_PKG="$PKG" node -e '
const fs = require("fs");
const f  = JSON.parse(fs.readFileSync(process.env.HOOK_PKG, "utf8"));
const c  = f.cds.requires.db.credentials;
c.host     = "sqlnotas.postgres.database.azure.com";
c.database = "notas";
c.user     = "sap";
c.password = "T69XgyE8%:u3";
c.schema   = "notas";
fs.writeFileSync(process.env.HOOK_PKG, JSON.stringify(f, null, 2) + "\n");
console.log("[post-commit] Entorno restaurado → rama DEV");
'
    ;;
  QAS)
    HOOK_PKG="$PKG" node -e '
const fs = require("fs");
const f  = JSON.parse(fs.readFileSync(process.env.HOOK_PKG, "utf8"));
const c  = f.cds.requires.db.credentials;
c.host     = "sqlnotas.postgres.database.azure.com";
c.database = "notas";
c.user     = "sap";
c.password = "T69XgyE8%:u3";
c.schema   = "notas_qa";
fs.writeFileSync(process.env.HOOK_PKG, JSON.stringify(f, null, 2) + "\n");
console.log("[post-commit] Entorno restaurado → rama QAS");
'
    ;;
  main)
    HOOK_PKG="$PKG" node -e '
const fs = require("fs");
const f  = JSON.parse(fs.readFileSync(process.env.HOOK_PKG, "utf8"));
const c  = f.cds.requires.db.credentials;
c.host     = "notasprod.postgres.database.azure.com";
c.database = "notas_prod";
c.user     = "sapnotasprod";
c.password = "XRgogaf7CKNw";
c.schema   = "notasprod";
fs.writeFileSync(process.env.HOOK_PKG, JSON.stringify(f, null, 2) + "\n");
console.log("[post-commit] Entorno restaurado → rama main");
'
    ;;
  *)
    exit 0
    ;;
esac
